services:
  react-app-postgres-db:
    #image: postgres:latest
    image: postgres:16.3-alpine3.20 #https://hub.docker.com/layers/library/postgres/16.3-alpine3.20/images/sha256-5eb2698ee6a3331df0788e1786145dc248e9a33e98dd161c4d1168a9fdf12a01?context=explore
    container_name: react-app-postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
      # Host Port (5433): This is the port your local machine (host) will use to communicate with the container.
      # Container Port (5432): PostgreSQL inside the container still listens on its default port (5432), but the host machine accesses it via 5433.
    volumes:
      #- postgres-db-volume:/var/lib/postgresql/data # /var/lib/postgresql/data is the default data directory for PostgreSQL inside the container
      - ./react-app-postgres-data:/var/lib/postgresql/data # /var/lib/postgresql/data is the default data directory for PostgreSQL inside the container
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql # Optional: initialize with SQL script
volumes:
  postgres-volume:
    name: react-app-postgres-db-volume
    #driver: local # Docker-managed volume
